### ISSUE TITLE
MSNStorageService: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [msndevs/msnp-sharp#101]
```
Is there a way I can avoid this error?

MSNStorageService: Object reference not set to an instance of an object.

   at MSNPSharp.MSNStorageService.GetProfileImpl(PartnerScenario scenario)
   at MSNPSharp.MSNStorageService.GetProfile()
   at MSNPSharp.ContactService.SetDefaults()
   at MSNPSharp.ContactService.<SynchronizeContactList>b__1(Object ,
ABFindContactsPagedCompletedEventArgs )
   at MSNPSharp.ContactService.<>c__DisplayClass10.<abRequest>b__d(Object
sender, ABFindContactsPagedCompletedEventArgs e)
   at
MSNPSharp.MSNWS.MSNABSharingService.ABServiceBinding.OnABFindContactsPagedOperat
ionCompleted(Object
arg)
```

Original issue reported on code.google.com by `johnpaul...@gmail.com` on 9 Apr 2009 at 5:49

**Comment by GoogleCodeExporter** [comment]
```
Please provide more information. You can step into our library to see what 
passed a 
null reference into the function.
```

Original comment by `freezing...@gmail.com` on 15 Apr 2009 at 6:56

**Comment by GoogleCodeExporter** [comment]
Original comment by `freezing...@gmail.com` on 18 Apr 2009 at 3:35
- Changed state: **Invalid**
