### ISSUE TITLE
System.NotSupportedException during ReverseAdded

### ISSUE THREAD

**Issue by GoogleCodeExporter** [msndevs/msnp-sharp#213]
```
I get this exception http://chaosstory.net/public/msnpsharp.png every time a 
contact adds the owner.

My Messenger.Nameserver.ContactService.ReverseAdded Function throws it.
The code in it is:
            Messenger.Nameserver.ContactService.AddNewContact(e.Contact.Mail)
            e.Contact.OnAllowedList = True
            e.Contact.OnForwardList = True
            e.Contact.OnBlockedList = False
            e.Contact.OnPendingList = False
            Messenger.Owner.Status = PresenceStatus.Online

It doesn't really give me much more information. When I restart the program it 
works fine next time.
Any ideas?

What version of the product are you using? (MSNPSharp, OS, Mono etc.)
MSNPSharp 302 Release.
```

Original issue reported on code.google.com by `matti_ko...@msn.com` on 13 Aug 2010 at 8:37

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Hi,

Could you please attach the picture once more? I can't see it. Sorry for the 
late reply because I just move to USA recently and not yet settle down.
```

Original comment by `freezing...@gmail.com` on 20 Aug 2010 at 10:45

**Comment by GoogleCodeExporter** [comment]
```
Should be online again. Sorry wasn't at home and didn't notice it went down.
```

Original comment by `matti_ko...@msn.com` on 22 Aug 2010 at 6:20

**Comment by GoogleCodeExporter** [comment]
```
Plase change your code like this:
            Messenger.Nameserver.ContactService.AddNewContact(e.Contact.Mail)
            e.Contact.OnAllowedList = True
            e.Contact.OnPendingList = False
            Messenger.Owner.Status = PresenceStatus.Online
```

Original comment by `freezing...@gmail.com` on 28 Aug 2010 at 1:51

**Comment by GoogleCodeExporter** [comment]
```
File: SecurityTokenServiceWrapper.cs
Function: GetReaderForMessage()
Line: 51, 57, 60, 65, 68,

Error: NetworkStream does not support seek operations

Affects: 3.0.2.1650 and DEV

Solution: Define a MemoryStream as innerStream, then write networkstream to 
memorystream. See 2.5. stable (MSNSecurityServiceSoapClient)

```

Original comment by `hepha...@gmail.com` on 28 Aug 2010 at 1:46

**Comment by GoogleCodeExporter** [comment]
Original comment by `freezing...@gmail.com` on 30 Aug 2010 at 8:45
- Changed state: **Fixed**
- Added labels: **Milestone-Release3.1.0**

**Comment by GoogleCodeExporter** [comment]
```
No difference.
One contact can be added but a second one throws:

System.NotSupportedException: This stream does not support seek operations.
   at System.Net.ConnectStream.get_Position()
   at MSNPSharp.SecurityTokenServiceWrapper.GetReaderForMessage(SoapClientMessage message, Int32 bufferSize)
   at System.Web.Services.Protocols.SoapHttpClientProtocol.ReadResponse(SoapClientMessage message, WebResponse response, Stream responseStream, Boolean asyncCall)
   at System.Web.Services.Protocols.SoapHttpClientProtocol.Invoke(String methodName, Object[] parameters)
   at MSNPSharp.MSNWS.MSNSecurityTokenService.SecurityTokenService.RequestMultipleSecurityTokens(RequestMultipleSecurityTokensType RequestMultipleSecurityTokens1)
   at MSNPSharp.SingleSignOn.Authenticate(SecurityTokenService securService, MSNTicket msnticket, Boolean async, EventHandler onSuccess, EventHandler`1 onError)
```

Original comment by `matti_ko...@msn.com` on 31 Aug 2010 at 6:26

**Comment by GoogleCodeExporter** [comment]
```
Please attach the trace log here.
```

Original comment by `freezing...@gmail.com` on 31 Aug 2010 at 10:51

**Comment by GoogleCodeExporter** [comment]
Original comment by `freezing...@gmail.com` on 31 Aug 2010 at 10:51
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
1. Check out the latest 30_STABLE
2. Do the test again.
3. If problem still there, attach the trace log in the trace form to here.
```

Original comment by `freezing...@gmail.com` on 31 Aug 2010 at 10:55

**Comment by GoogleCodeExporter** [comment]
Original comment by `hepha...@gmail.com` on 5 Sep 2010 at 3:40
- Changed state: **Fixed**
- Added labels: **Milestone-Release3.0.3**
- Removed labels: **Milestone-Release3.1.0**
