### ISSUE TITLE
Hidden Contact with Same PUID Already Exists

### ISSUE THREAD

**Issue by GoogleCodeExporter** [msndevs/msnp-sharp#249]
```
What steps will reproduce the problem?
1. A login DotMsnClient
2. B login windows live messenger client 
3. B add A to its contact list
4. A accept B and add it to its contact list

What is the expected output? What do you see instead?
B should appear on A's contact list and B should see A online and vice verse.
But what I see is that B is not on A's list.
Instead, i see the exception in the trace form:
ContactService: DeleteMember completed: PendingList
ContactService: ABContactAdd: System.Web.Services.Protocols.SoapException: 
Hidden Contact with Same PUID Already Exists 
   at System.Web.Services.Protocols.SoapHttpClientProtocol.ReadResponse(SoapClientMessage message, WebResponse response, Stream responseStream, Boolean asyncCall)
   at System.Web.Services.Protocols.SoapHttpClientProtocol.InvokeAsyncCallback(IAsyncResult result)
ContactService: DeleteMember: System.Web.Services.Protocols.SoapException: 
Member does not exist 
   at System.Web.Services.Protocols.SoapHttpClientProtocol.ReadResponse(SoapClientMessage message, WebResponse response, Stream responseStream, Boolean asyncCall)
   at System.Web.Services.Protocols.SoapHttpClientProtocol.InvokeAsyncCallback(IAsyncResult result)
ContactService: DeleteMember completed: PendingList


What version of the product are you using? (MSNPSharp, OS, Mono etc.)

Is your code check out from SVN or download from our download site?
latest truck from svn

Please provide any additional information below:
I will try 3.1 stable code to see if the same problem exists.

```

Original issue reported on code.google.com by `shoujies...@gmail.com` on 26 Jan 2011 at 2:06

**Comment by GoogleCodeExporter** [comment]
```
I just repeat the steps on 3.1.1 stable code and find the same exception 
happened.
```

Original comment by `shoujies...@gmail.com` on 26 Jan 2011 at 2:20

**Comment by GoogleCodeExporter** [comment]
```
It is the first time for A to add contact B. So the soap message is strange to 
me.
```

Original comment by `shoujies...@gmail.com` on 26 Jan 2011 at 2:24

**Comment by GoogleCodeExporter** [comment]
```
To reproduce the issue:

1) Download and Install Fiddler: http://www.fiddler2.com/fiddler2/version.asp
2) Open Fiddler2 and select "AutoDecode" button to decompress gzip 
automatically. From menu, select Tools - Fiddler Options - HTTPs. Tick capture 
https, decrypt https and install temporary certificates displayed. Restart 
Fiddler2.
3) Open msnpsharp example client and accept invitation. Don't close fiddler.
3) Open official client and accept again. Don't close fiddler.
4) Fiddler - File - Save - all sessions and attach the fiddler.saz here.
```

Original comment by `hepha...@gmail.com` on 27 Jan 2011 at 12:57

**Comment by GoogleCodeExporter** [comment]
```
I followed you steps to reproduce the problem. the same error message happened 
again.

In your step 3, when i opened the official client, there was no invitation 
prompted. instead, i accepted the invitation by a link appeared on the 
messenger on the web.

All steps are recorded in the attachment file per your instruction. Thank you 
for a quick response :-)
```

Original comment by `shoujies...@gmail.com` on 27 Jan 2011 at 2:59

Attachments:
- [msnpsharp.saz](https://storage.googleapis.com/google-code-attachments/msnp-sharp/issue-249/comment-4/msnpsharp.saz)

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Hi,
Can you repeat the same procedure again with a WLM client and send us the 
captured data?
```

Original comment by `freezing...@gmail.com` on 27 Jan 2011 at 7:56

**Comment by GoogleCodeExporter** [comment]
```
Client A sent invitation to Client B.
It seems working well on WLM. my client version is 2009(14.0.8117.416)
```

Original comment by `shoujies...@gmail.com` on 28 Jan 2011 at 1:54

Attachments:
- [clientA.saz](https://storage.googleapis.com/google-code-attachments/msnp-sharp/issue-249/comment-7/clientA.saz)
- [clientB.saz](https://storage.googleapis.com/google-code-attachments/msnp-sharp/issue-249/comment-7/clientB.saz)

**Comment by GoogleCodeExporter** [comment]
Original comment by `freezing...@gmail.com` on 29 Jan 2011 at 2:11
- Added labels: **Priority-High**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
```
Ethem,

In line 1192 of ContactService.cs, I think it should be 
request.contacts[0].contactInfo.contactType = MessengerContactType.LivePending;

Just look at official client's behavior, I want to change this a long time ago, 
but not sure I am right or not.
```

Original comment by `freezing...@gmail.com` on 29 Jan 2011 at 2:23

**Comment by GoogleCodeExporter** [comment]
```
And there's also a ABFindByContacts call, but I don't know from where it get 
the guid.
```

Original comment by `freezing...@gmail.com` on 29 Jan 2011 at 5:44

**Comment by GoogleCodeExporter** [comment]
```
I don't think so contactType=regular is problem. See r746 log. The contact 
couldn't added if added before. It generates a new error: "Dynamic item already 
exists"

The official client generates the same error, but it doesn't show any warning.
See attached clientb.saz, no:68...
The contact GUID is here: conflictObjectId

{{{
<?xml version="1.0" encoding="utf-8"?><soap:Envelope 
xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><soap:Fault><faultcode>s
oap:Client</faultcode><faultstring>Hidden Contact with Same PUID Already Exists 
</faultstring><faultactor>http://www.msn.com/webservices/AddressBook/ABContactAd
d</faultactor><detail><errorcode 
xmlns="http://www.msn.com/webservices/AddressBook">ContactAlreadyExists</errorco
de><errorstring xmlns="http://www.msn.com/webservices/AddressBook">Hidden 
Contact with Same PUID Already Exists </errorstring><machineName 
xmlns="http://www.msn.com/webservices/AddressBook">SN1ABCHWB68</machineName><add
itionalDetails><conflictObjectId>EBEC29B8-FD5F-4E50-A258-0FE54B3C484F</conflictO
bjectId></additionalDetails></detail></soap:Fault></soap:Body></soap:Envelope>
}}}
```

Original comment by `hepha...@gmail.com` on 29 Jan 2011 at 9:15

**Comment by GoogleCodeExporter** [comment]
```
Hi, thanks for looking into the problem.
For testing purpose, I register 2 new accounts. So I think it is the first time 
for A to add B into its contact list.
```

Original comment by `shoujies...@gmail.com` on 29 Jan 2011 at 9:31

**Comment by GoogleCodeExporter** [comment]
```
You welcome,

Pang got the point to solve this issue. Please wait the fix...

Official client does:

1- If Hidden Contact with Same PUID Already Exists, inserts contact guid into 
conflictObjectId tag.
2- Calls ABFindByContacts soap function to get contact.
3- Calls ABContactUpdate with IsMessengerUser MessengerMemberInfo properties.

Thank you for the report again. 

```

Original comment by `hepha...@gmail.com` on 29 Jan 2011 at 9:48

**Comment by GoogleCodeExporter** [comment]
```
Owner is Pang. :)
```

Original comment by `hepha...@gmail.com` on 29 Jan 2011 at 9:53
- Changed state: **Started**
- Added labels: **Milestone-Release3.1.2**

**Comment by GoogleCodeExporter** [comment]
```
Ah, I've ignored #68, no wonder.. let me fix it.
```

Original comment by `freezing...@gmail.com` on 29 Jan 2011 at 6:28

**Comment by GoogleCodeExporter** [comment]
```
I've fixed it in the trunk, Ethem could you please merge it to 3.1?
```

Original comment by `freezing...@gmail.com` on 30 Jan 2011 at 5:22

**Comment by GoogleCodeExporter** [comment]
```
This issue was updated by revision r1957.
```

Original comment by `hepha...@gmail.com` on 30 Jan 2011 at 10:50
- Changed state: **Fixed**
