### ISSUE TITLE
Error on XMLContactList.AddMemberhip

### ISSUE THREAD

**Issue by GoogleCodeExporter** [msndevs/msnp-sharp#49]
```
What steps will reproduce the problem?
1. enter username and password to login
2. the app begins to authenticate，after it, it begins to get friends data
3. after all,error begins

What is the expected output? What do you see instead?
output is fine,when recieves a message,it can be traced yet

What version of the product are you using? On what operating system?
svn 2.5

Please provide any additional information below.
hey,it is me again :) 
it seems that the error will be found some time,but some time not

trace code-------------------
未处理 System.Reflection.TargetInvocationException
  Message="Exception has been thrown by the target of an invocation."
  Source="mscorlib"
  StackTrace:
       at System.RuntimeMethodHandle._InvokeMethodFast(Object target, 
Object[] arguments, SignatureStruct& sig, MethodAttributes 
methodAttributes, RuntimeTypeHandle typeOwner)
       at System.RuntimeMethodHandle.InvokeMethodFast(Object target, Object
[] arguments, Signature sig, MethodAttributes methodAttributes, 
RuntimeTypeHandle typeOwner)
       at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, 
BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo 
culture, Boolean skipVisibilityChecks)
       at System.Delegate.DynamicInvokeImpl(Object[] args)
       at System.Windows.Forms.Control.InvokeMarshaledCallbackDo
(ThreadMethodEntry tme)
       at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper
(Object obj)
       at System.Threading.ExecutionContext.runTryCode(Object userData)
       at 
System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCle
anup(TryCode code, CleanupCode backoutCode, Object userData)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext 
executionContext, ContextCallback callback, Object state)
       at System.Threading.ExecutionContext.Run(ExecutionContext 
executionContext, ContextCallback callback, Object state)
       at System.Windows.Forms.Control.InvokeMarshaledCallback
(ThreadMethodEntry tme)
       at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
       at System.Windows.Forms.Control.WndProc(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.OnMessage
(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.WndProc
(Message& m)
       at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr 
hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
       at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& 
msg)
       at 
System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.Unsa
feNativeMethods.IMsoComponentManager.FPushMessageLoop(Int32 dwComponentID, 
Int32 reason, Int32 pvLoopData)
       at 
System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 
reason, ApplicationContext context)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoop
(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.Run(Form mainForm)
       at MSNPSharpClient.ClientForm.Main() in 
D:\Users\edwin\Desktop\msn\Example\DotMSNClient.cs:line 753
       at System.AppDomain._nExecuteAssembly(Assembly assembly, String[] 
args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence 
assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.Run(ExecutionContext 
executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: System.ArgumentException
       Message="An item with the same key has already been added."
       Source="mscorlib"
       StackTrace:
            at System.ThrowHelper.ThrowArgumentException(ExceptionResource 
resource)
            at System.Collections.Generic.Dictionary`2.Insert(TKey key, 
TValue value, Boolean add)
            at System.Collections.Generic.Dictionary`2.Add(TKey key, 
TValue value)
            at MSNPSharp.IO.XMLContactList.AddMemberhip(ServiceFilterType 
servicetype, String account, ClientType type, MemberRole memberrole, 
BaseMember member) in 
D:\Users\edwin\Desktop\msn\MSNPSharp\IO\XMLContactList.cs:line 195
            at MSNPSharp.IO.XMLContactList.op_Addition(XMLContactList 
xmlcl, FindMembershipResultType findMembership) in 
D:\Users\edwin\Desktop\msn\MSNPSharp\IO\XMLContactList.cs:line 325
            at MSNPSharp.ContactService.<>c__DisplayClassa.<msRequest>b__6
(Object sender, FindMembershipCompletedEventArgs e) in 
D:\Users\edwin\Desktop\msn\MSNPSharp\ContactService.cs:line 484
            at 
MSNPSharp.MSNWS.MSNABSharingService.SharingServiceBinding.OnFindMembershipO
perationCompleted(Object arg) in D:\Users\edwin\Desktop\msn\MSNPSharp\Web 
References\MSNWS.MSNABSharingService\Reference.cs:line 149
       InnerException: 


```

Original issue reported on code.google.com by `edwintai...@gmail.com` on 21 Nov 2008 at 4:51

**Comment by GoogleCodeExporter** [comment]
```
i have found the solution
error message is Message="An item with the same key has already been added."
at MSNPSharp.IO.XMLContactList.AddMemberhip(ServiceFilterType servicetype, 
String 
account, ClientType type, MemberRole memberrole, BaseMember member)
Have you seen it?
Judge it before insert
please fix it,thanks
```

Original comment by `edwintai...@gmail.com` on 21 Nov 2008 at 4:54

**Comment by GoogleCodeExporter** [comment]
Original comment by `hepha...@gmail.com` on 21 Nov 2008 at 8:56
- Changed title: **Error on XMLContactList.AddMemberhip**
- Changed state: **Fixed**
- Added labels: **Milestone-Release2.5.2**

**Comment by GoogleCodeExporter** [comment]
```
Message="An item with the same key has already been added."
May be you have 2 key with the same value. 
I had a same this error in the past.

-------------------
Dung Nguyen
Web Developer
www.lolvemusic.de.tl

```

Original comment by `dung1582...@gmail.com` on 30 Dec 2008 at 7:16
